
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home.php">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Member
          </a>
          <ul class="dropdown-menu ulcustomize" aria-labelledby="navbarDropdown" style="border-radius: 0%">
            <li>
              <a class="dropdown-item" href="addmember.php">Add Member</a>
            </li>
            <li>
              <a class="dropdown-item" href="findmember.php">Find Member</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="checkout.php">Check Out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="sales.php">Sales</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="index.php">Log Out</a>
        </li>
      </ul>
    </div>
  </nav>
